import { getCharacterDef } from './characters';
import type { CardDef, CardInstance, CardRarity, CharacterId } from './types';

/**
 * Card database. Data-driven: adding a card means adding an entry here.
 * Descriptions are generated by the UI layer from effects, not stored here.
 */
export const CARDS: Record<string, CardDef> = {};

function define(def: CardDef): void {
  if (CARDS[def.id]) throw new Error(`Duplicate card id: ${def.id}`);
  CARDS[def.id] = def;
}

define({
  id: 'strike',
  name: 'Strike',
  type: 'attack',
  rarity: 'starter',
  cost: 1,
  target: 'enemy',
  effects: [{ kind: 'damage', amount: 6 }],
  upgrade: { effects: [{ kind: 'damage', amount: 9 }] },
});

define({
  id: 'defend',
  name: 'Defend',
  type: 'skill',
  rarity: 'starter',
  cost: 1,
  target: 'none',
  effects: [{ kind: 'block', amount: 5 }],
  upgrade: { effects: [{ kind: 'block', amount: 8 }] },
});

define({
  id: 'bash',
  name: 'Bash',
  type: 'attack',
  rarity: 'starter',
  cost: 2,
  target: 'enemy',
  effects: [
    { kind: 'damage', amount: 8 },
    { kind: 'applyStatus', status: 'vulnerable', stacks: 2, target: 'enemy' },
  ],
  upgrade: {
    effects: [
      { kind: 'damage', amount: 10 },
      { kind: 'applyStatus', status: 'vulnerable', stacks: 3, target: 'enemy' },
    ],
  },
});

define({
  id: 'cleave',
  name: 'Cleave',
  type: 'attack',
  rarity: 'common',
  cost: 1,
  target: 'none',
  effects: [{ kind: 'damage', amount: 8, target: 'allEnemies' }],
  upgrade: { effects: [{ kind: 'damage', amount: 11, target: 'allEnemies' }] },
});

define({
  id: 'pommel_strike',
  name: 'Pommel Strike',
  type: 'attack',
  rarity: 'common',
  cost: 1,
  target: 'enemy',
  effects: [
    { kind: 'damage', amount: 9 },
    { kind: 'draw', count: 1 },
  ],
  upgrade: {
    effects: [
      { kind: 'damage', amount: 10 },
      { kind: 'draw', count: 2 },
    ],
  },
});

define({
  id: 'twin_strike',
  name: 'Twin Strike',
  type: 'attack',
  rarity: 'common',
  cost: 1,
  target: 'enemy',
  effects: [{ kind: 'damage', amount: 5, times: 2 }],
  upgrade: { effects: [{ kind: 'damage', amount: 7, times: 2 }] },
});

define({
  id: 'iron_wave',
  name: 'Iron Wave',
  type: 'attack',
  rarity: 'common',
  cost: 1,
  target: 'enemy',
  effects: [
    { kind: 'damage', amount: 5 },
    { kind: 'block', amount: 5 },
  ],
  upgrade: {
    effects: [
      { kind: 'damage', amount: 7 },
      { kind: 'block', amount: 7 },
    ],
  },
});

define({
  id: 'shrug_it_off',
  name: 'Shrug It Off',
  type: 'skill',
  rarity: 'common',
  cost: 1,
  target: 'none',
  effects: [
    { kind: 'block', amount: 8 },
    { kind: 'draw', count: 1 },
  ],
  upgrade: {
    effects: [
      { kind: 'block', amount: 11 },
      { kind: 'draw', count: 1 },
    ],
  },
});

define({
  id: 'deadly_venom',
  name: 'Deadly Venom',
  type: 'skill',
  rarity: 'uncommon',
  cost: 1,
  target: 'enemy',
  effects: [{ kind: 'applyStatus', status: 'poison', stacks: 5, target: 'enemy' }],
  upgrade: { effects: [{ kind: 'applyStatus', status: 'poison', stacks: 7, target: 'enemy' }] },
});

define({
  id: 'inflame',
  name: 'Inflame',
  type: 'power',
  rarity: 'uncommon',
  cost: 1,
  target: 'none',
  effects: [{ kind: 'applyStatus', status: 'strength', stacks: 2, target: 'self' }],
  upgrade: { effects: [{ kind: 'applyStatus', status: 'strength', stacks: 3, target: 'self' }] },
});

define({
  id: 'bludgeon',
  name: 'Bludgeon',
  type: 'attack',
  rarity: 'rare',
  cost: 3,
  target: 'enemy',
  effects: [{ kind: 'damage', amount: 32 }],
  upgrade: { effects: [{ kind: 'damage', amount: 42 }] },
});

define({
  id: 'offering',
  name: 'Offering',
  type: 'skill',
  rarity: 'rare',
  cost: 0,
  target: 'none',
  exhaust: true,
  effects: [
    { kind: 'loseHp', amount: 6 },
    { kind: 'gainEnergy', amount: 2 },
    { kind: 'draw', count: 3 },
  ],
  upgrade: {
    effects: [
      { kind: 'loseHp', amount: 6 },
      { kind: 'gainEnergy', amount: 2 },
      { kind: 'draw', count: 5 },
    ],
  },
});

// --- Day 7 pool expansion ---

define({
  id: 'anger',
  name: 'Anger',
  type: 'attack',
  rarity: 'common',
  cost: 0,
  target: 'enemy',
  // Copies are always unupgraded (simplification vs StS).
  effects: [
    { kind: 'damage', amount: 6 },
    { kind: 'addCard', card: 'anger', destination: 'discardPile' },
  ],
  upgrade: {
    effects: [
      { kind: 'damage', amount: 8 },
      { kind: 'addCard', card: 'anger', destination: 'discardPile' },
    ],
  },
});

define({
  id: 'sucker_punch',
  name: 'Sucker Punch',
  type: 'attack',
  rarity: 'common',
  cost: 1,
  target: 'enemy',
  effects: [
    { kind: 'damage', amount: 7 },
    { kind: 'applyStatus', status: 'weak', stacks: 1, target: 'enemy' },
  ],
  upgrade: {
    effects: [
      { kind: 'damage', amount: 9 },
      { kind: 'applyStatus', status: 'weak', stacks: 2, target: 'enemy' },
    ],
  },
});

define({
  id: 'wild_strike',
  name: 'Wild Strike',
  type: 'attack',
  rarity: 'common',
  cost: 1,
  target: 'enemy',
  effects: [
    { kind: 'damage', amount: 12 },
    { kind: 'addCard', card: 'wound', destination: 'drawPile' },
  ],
  upgrade: {
    effects: [
      { kind: 'damage', amount: 17 },
      { kind: 'addCard', card: 'wound', destination: 'drawPile' },
    ],
  },
});

define({
  id: 'reckless_charge',
  name: 'Reckless Charge',
  type: 'attack',
  rarity: 'common',
  cost: 0,
  target: 'enemy',
  effects: [
    { kind: 'damage', amount: 7 },
    { kind: 'addCard', card: 'wound', destination: 'drawPile' },
  ],
  upgrade: {
    effects: [
      { kind: 'damage', amount: 10 },
      { kind: 'addCard', card: 'wound', destination: 'drawPile' },
    ],
  },
});

define({
  id: 'backflip',
  name: 'Backflip',
  type: 'skill',
  rarity: 'common',
  cost: 1,
  target: 'none',
  effects: [
    { kind: 'block', amount: 5 },
    { kind: 'draw', count: 2 },
  ],
  upgrade: {
    effects: [
      { kind: 'block', amount: 8 },
      { kind: 'draw', count: 2 },
    ],
  },
});

define({
  id: 'heavy_armor',
  name: 'Heavy Armor',
  type: 'skill',
  rarity: 'common',
  cost: 2,
  target: 'none',
  effects: [{ kind: 'block', amount: 13 }],
  upgrade: { effects: [{ kind: 'block', amount: 17 }] },
});

define({
  id: 'bloodletting',
  name: 'Bloodletting',
  type: 'skill',
  rarity: 'common',
  cost: 0,
  target: 'none',
  effects: [
    { kind: 'loseHp', amount: 3 },
    { kind: 'gainEnergy', amount: 2 },
  ],
  upgrade: {
    effects: [
      { kind: 'loseHp', amount: 2 },
      { kind: 'gainEnergy', amount: 2 },
    ],
  },
});

define({
  id: 'battle_trance',
  name: 'Battle Trance',
  type: 'skill',
  rarity: 'common',
  cost: 0,
  target: 'none',
  effects: [{ kind: 'draw', count: 3 }],
  upgrade: { effects: [{ kind: 'draw', count: 4 }] },
});

define({
  id: 'clothesline',
  name: 'Clothesline',
  type: 'attack',
  rarity: 'uncommon',
  cost: 2,
  target: 'enemy',
  effects: [
    { kind: 'damage', amount: 12 },
    { kind: 'applyStatus', status: 'weak', stacks: 2, target: 'enemy' },
  ],
  upgrade: {
    effects: [
      { kind: 'damage', amount: 14 },
      { kind: 'applyStatus', status: 'weak', stacks: 3, target: 'enemy' },
    ],
  },
});

define({
  id: 'uppercut',
  name: 'Uppercut',
  type: 'attack',
  rarity: 'uncommon',
  cost: 2,
  target: 'enemy',
  effects: [
    { kind: 'damage', amount: 13 },
    { kind: 'applyStatus', status: 'weak', stacks: 1, target: 'enemy' },
    { kind: 'applyStatus', status: 'vulnerable', stacks: 1, target: 'enemy' },
  ],
  upgrade: {
    effects: [
      { kind: 'damage', amount: 13 },
      { kind: 'applyStatus', status: 'weak', stacks: 2, target: 'enemy' },
      { kind: 'applyStatus', status: 'vulnerable', stacks: 2, target: 'enemy' },
    ],
  },
});

define({
  id: 'hemokinesis',
  name: 'Hemokinesis',
  type: 'attack',
  rarity: 'uncommon',
  cost: 1,
  target: 'enemy',
  effects: [
    { kind: 'loseHp', amount: 2 },
    { kind: 'damage', amount: 15 },
  ],
  upgrade: {
    effects: [
      { kind: 'loseHp', amount: 2 },
      { kind: 'damage', amount: 20 },
    ],
  },
});

define({
  id: 'pummel',
  name: 'Pummel',
  type: 'attack',
  rarity: 'uncommon',
  cost: 1,
  target: 'enemy',
  exhaust: true,
  effects: [{ kind: 'damage', amount: 2, times: 4 }],
  upgrade: { effects: [{ kind: 'damage', amount: 2, times: 5 }] },
});

define({
  id: 'venom_strike',
  name: 'Venom Strike',
  type: 'attack',
  rarity: 'uncommon',
  cost: 1,
  target: 'enemy',
  effects: [
    { kind: 'damage', amount: 6 },
    { kind: 'applyStatus', status: 'poison', stacks: 3, target: 'enemy' },
  ],
  upgrade: {
    effects: [
      { kind: 'damage', amount: 8 },
      { kind: 'applyStatus', status: 'poison', stacks: 4, target: 'enemy' },
    ],
  },
});

define({
  id: 'dash',
  name: 'Dash',
  type: 'attack',
  rarity: 'uncommon',
  cost: 2,
  target: 'enemy',
  effects: [
    { kind: 'block', amount: 10 },
    { kind: 'damage', amount: 10 },
  ],
  upgrade: {
    effects: [
      { kind: 'block', amount: 13 },
      { kind: 'damage', amount: 13 },
    ],
  },
});

define({
  id: 'disarm',
  name: 'Disarm',
  type: 'skill',
  rarity: 'uncommon',
  cost: 1,
  target: 'enemy',
  exhaust: true,
  effects: [{ kind: 'applyStatus', status: 'strength', stacks: -2, target: 'enemy' }],
  upgrade: { effects: [{ kind: 'applyStatus', status: 'strength', stacks: -3, target: 'enemy' }] },
});

define({
  id: 'flex',
  name: 'Flex',
  type: 'skill',
  rarity: 'common',
  cost: 0,
  target: 'none',
  exhaust: true,
  effects: [{ kind: 'applyStatus', status: 'strength', stacks: 1, target: 'self' }],
  upgrade: { effects: [{ kind: 'applyStatus', status: 'strength', stacks: 2, target: 'self' }] },
});

define({
  id: 'shockwave',
  name: 'Shockwave',
  type: 'skill',
  rarity: 'uncommon',
  cost: 2,
  target: 'none',
  exhaust: true,
  effects: [
    { kind: 'applyStatus', status: 'weak', stacks: 3, target: 'allEnemies' },
    { kind: 'applyStatus', status: 'vulnerable', stacks: 3, target: 'allEnemies' },
  ],
  upgrade: {
    effects: [
      { kind: 'applyStatus', status: 'weak', stacks: 5, target: 'allEnemies' },
      { kind: 'applyStatus', status: 'vulnerable', stacks: 5, target: 'allEnemies' },
    ],
  },
});

define({
  id: 'terror',
  name: 'Terror',
  type: 'skill',
  rarity: 'uncommon',
  cost: 1,
  target: 'enemy',
  exhaust: true,
  effects: [{ kind: 'applyStatus', status: 'vulnerable', stacks: 5, target: 'enemy' }],
  upgrade: { cost: 0 },
});

define({
  id: 'shiv',
  name: 'Shiv',
  type: 'attack',
  rarity: 'special',
  cost: 0,
  target: 'enemy',
  exhaust: true,
  effects: [{ kind: 'damage', amount: 4 }],
  upgrade: { effects: [{ kind: 'damage', amount: 6 }] },
});

define({
  id: 'blade_dance',
  name: 'Blade Dance',
  type: 'skill',
  rarity: 'uncommon',
  cost: 1,
  target: 'none',
  effects: [{ kind: 'addCard', card: 'shiv', count: 3, destination: 'hand' }],
  upgrade: { effects: [{ kind: 'addCard', card: 'shiv', count: 4, destination: 'hand' }] },
});

define({
  id: 'cloak_and_dagger',
  name: 'Cloak and Dagger',
  type: 'skill',
  rarity: 'common',
  cost: 1,
  target: 'none',
  effects: [
    { kind: 'block', amount: 6 },
    { kind: 'addCard', card: 'shiv', count: 1, destination: 'hand' },
  ],
  upgrade: {
    effects: [
      { kind: 'block', amount: 6 },
      { kind: 'addCard', card: 'shiv', count: 2, destination: 'hand' },
    ],
  },
});

define({
  id: 'adrenaline',
  name: 'Adrenaline',
  type: 'skill',
  rarity: 'rare',
  cost: 0,
  target: 'none',
  exhaust: true,
  effects: [
    { kind: 'gainEnergy', amount: 1 },
    { kind: 'draw', count: 2 },
  ],
  upgrade: {
    effects: [
      { kind: 'gainEnergy', amount: 2 },
      { kind: 'draw', count: 2 },
    ],
  },
});

define({
  id: 'impervious',
  name: 'Impervious',
  type: 'skill',
  rarity: 'rare',
  cost: 2,
  target: 'none',
  exhaust: true,
  effects: [{ kind: 'block', amount: 30 }],
  upgrade: { effects: [{ kind: 'block', amount: 40 }] },
});

define({
  id: 'demon_form',
  name: 'Demon Form',
  type: 'power',
  rarity: 'rare',
  cost: 3,
  target: 'none',
  effects: [{ kind: 'applyStatus', status: 'ritual', stacks: 2, target: 'self' }],
  upgrade: { effects: [{ kind: 'applyStatus', status: 'ritual', stacks: 3, target: 'self' }] },
});

define({
  id: 'berserk',
  name: 'Berserk',
  type: 'power',
  rarity: 'rare',
  cost: 0,
  target: 'none',
  effects: [
    { kind: 'applyStatus', status: 'vulnerable', stacks: 2, target: 'self' },
    { kind: 'applyStatus', status: 'energized', stacks: 1, target: 'self' },
  ],
  upgrade: {
    effects: [
      { kind: 'applyStatus', status: 'vulnerable', stacks: 1, target: 'self' },
      { kind: 'applyStatus', status: 'energized', stacks: 1, target: 'self' },
    ],
  },
});

// --- Day 9 pool expansion ---

define({
  id: 'quick_slash',
  name: 'Quick Slash',
  type: 'attack',
  rarity: 'common',
  cost: 1,
  target: 'enemy',
  effects: [
    { kind: 'damage', amount: 8 },
    { kind: 'draw', count: 1 },
  ],
  upgrade: {
    effects: [
      { kind: 'damage', amount: 12 },
      { kind: 'draw', count: 1 },
    ],
  },
});

define({
  id: 'flurry',
  name: 'Flurry',
  type: 'attack',
  rarity: 'common',
  cost: 0,
  target: 'enemy',
  effects: [{ kind: 'damage', amount: 3, times: 2 }],
  upgrade: { effects: [{ kind: 'damage', amount: 4, times: 2 }] },
});

define({
  id: 'heavy_blade',
  name: 'Heavy Blade',
  type: 'attack',
  rarity: 'common',
  cost: 2,
  target: 'enemy',
  effects: [{ kind: 'damage', amount: 16 }],
  upgrade: { effects: [{ kind: 'damage', amount: 22 }] },
});

define({
  id: 'trip',
  name: 'Trip',
  type: 'skill',
  rarity: 'common',
  cost: 1,
  target: 'enemy',
  effects: [{ kind: 'applyStatus', status: 'vulnerable', stacks: 2, target: 'enemy' }],
  upgrade: { effects: [{ kind: 'applyStatus', status: 'vulnerable', stacks: 3, target: 'enemy' }] },
});

define({
  id: 'emergency_guard',
  name: 'Emergency Guard',
  type: 'skill',
  rarity: 'common',
  cost: 0,
  target: 'none',
  exhaust: true,
  effects: [{ kind: 'block', amount: 9 }],
  upgrade: { effects: [{ kind: 'block', amount: 13 }] },
});

define({
  id: 'intimidate',
  name: 'Intimidate',
  type: 'skill',
  rarity: 'common',
  cost: 0,
  target: 'none',
  exhaust: true,
  effects: [{ kind: 'applyStatus', status: 'weak', stacks: 1, target: 'allEnemies' }],
  upgrade: { effects: [{ kind: 'applyStatus', status: 'weak', stacks: 2, target: 'allEnemies' }] },
});

define({
  id: 'noxious_blast',
  name: 'Noxious Blast',
  type: 'skill',
  rarity: 'uncommon',
  cost: 1,
  target: 'none',
  effects: [{ kind: 'applyStatus', status: 'poison', stacks: 3, target: 'allEnemies' }],
  upgrade: { effects: [{ kind: 'applyStatus', status: 'poison', stacks: 5, target: 'allEnemies' }] },
});

define({
  id: 'skewer',
  name: 'Skewer',
  type: 'attack',
  rarity: 'uncommon',
  cost: 'x',
  target: 'enemy',
  effects: [{ kind: 'damage', amount: 7, times: 'x' }],
  upgrade: { effects: [{ kind: 'damage', amount: 9, times: 'x' }] },
});

define({
  id: 'entrench',
  name: 'Entrench',
  type: 'skill',
  rarity: 'uncommon',
  cost: 2,
  target: 'none',
  effects: [{ kind: 'doubleBlock' }],
  upgrade: { cost: 1 },
});

define({
  id: 'seeing_red',
  name: 'Seeing Red',
  type: 'skill',
  rarity: 'uncommon',
  cost: 1,
  target: 'none',
  exhaust: true,
  effects: [{ kind: 'gainEnergy', amount: 2 }],
  upgrade: { cost: 0 },
});

define({
  id: 'footwork',
  name: 'Footwork',
  type: 'power',
  rarity: 'uncommon',
  cost: 1,
  target: 'none',
  effects: [{ kind: 'applyStatus', status: 'dexterity', stacks: 2, target: 'self' }],
  upgrade: { effects: [{ kind: 'applyStatus', status: 'dexterity', stacks: 3, target: 'self' }] },
});

define({
  id: 'caltrops',
  name: 'Caltrops',
  type: 'power',
  rarity: 'uncommon',
  cost: 1,
  target: 'none',
  effects: [{ kind: 'applyStatus', status: 'thorns', stacks: 3, target: 'self' }],
  upgrade: { effects: [{ kind: 'applyStatus', status: 'thorns', stacks: 5, target: 'self' }] },
});

define({
  id: 'die_die_die',
  name: 'Die Die Die',
  type: 'attack',
  rarity: 'rare',
  cost: 1,
  target: 'none',
  exhaust: true,
  effects: [{ kind: 'damage', amount: 13, target: 'allEnemies' }],
  upgrade: { effects: [{ kind: 'damage', amount: 17, target: 'allEnemies' }] },
});

define({
  id: 'barricade',
  name: 'Barricade',
  type: 'power',
  rarity: 'rare',
  cost: 3,
  target: 'none',
  effects: [{ kind: 'applyStatus', status: 'barricade', stacks: 1, target: 'self' }],
  upgrade: { cost: 2 },
});

define({
  id: 'noxious_fumes',
  name: 'Noxious Fumes',
  type: 'power',
  rarity: 'rare',
  cost: 1,
  target: 'none',
  effects: [{ kind: 'applyStatus', status: 'noxious', stacks: 2, target: 'self' }],
  upgrade: { effects: [{ kind: 'applyStatus', status: 'noxious', stacks: 3, target: 'self' }] },
});

// --- Status & curse cards (unplayable junk that clogs the deck) ---

define({
  id: 'wound',
  name: 'Wound',
  type: 'status',
  rarity: 'special',
  cost: 0,
  target: 'none',
  unplayable: true,
  effects: [],
});

define({
  id: 'burn',
  name: 'Burn',
  type: 'status',
  rarity: 'special',
  cost: 0,
  target: 'none',
  unplayable: true,
  selfDamageAtTurnEnd: 2,
  effects: [],
});

define({
  id: 'injury',
  name: 'Injury',
  type: 'curse',
  rarity: 'special',
  cost: 0,
  target: 'none',
  unplayable: true,
  effects: [],
});

// --- Day 2 playable cards ---

define({
  id: 'whirlwind',
  name: 'Whirlwind',
  type: 'attack',
  rarity: 'uncommon',
  cost: 'x',
  target: 'none',
  effects: [{ kind: 'damage', amount: 5, times: 'x', target: 'allEnemies' }],
  upgrade: { effects: [{ kind: 'damage', amount: 8, times: 'x', target: 'allEnemies' }] },
});

define({
  id: 'metallicize',
  name: 'Metallicize',
  type: 'power',
  rarity: 'uncommon',
  cost: 1,
  target: 'none',
  effects: [{ kind: 'applyStatus', status: 'metallicize', stacks: 3, target: 'self' }],
  upgrade: { effects: [{ kind: 'applyStatus', status: 'metallicize', stacks: 4, target: 'self' }] },
});

define({
  id: 'dramatic_entrance',
  name: 'Dramatic Entrance',
  type: 'attack',
  rarity: 'uncommon',
  cost: 0,
  target: 'none',
  innate: true,
  exhaust: true,
  effects: [{ kind: 'damage', amount: 8, target: 'allEnemies' }],
  upgrade: { effects: [{ kind: 'damage', amount: 12, target: 'allEnemies' }] },
});

// --- Assassin starter cards ---

define({
  id: 'neutralize',
  name: 'Neutralize',
  type: 'attack',
  rarity: 'starter',
  cost: 0,
  target: 'enemy',
  effects: [
    { kind: 'damage', amount: 3 },
    { kind: 'applyStatus', status: 'weak', stacks: 1, target: 'enemy' },
  ],
  upgrade: {
    effects: [
      { kind: 'damage', amount: 4 },
      { kind: 'applyStatus', status: 'weak', stacks: 2, target: 'enemy' },
    ],
  },
});

define({
  // Original discards a card; this engine has no discard-from-hand effect yet.
  id: 'survivor',
  name: 'Survivor',
  type: 'skill',
  rarity: 'starter',
  cost: 1,
  target: 'none',
  effects: [{ kind: 'block', amount: 8 }],
  upgrade: { effects: [{ kind: 'block', amount: 11 }] },
});

define({
  id: 'crippling_cloud',
  name: 'Crippling Cloud',
  type: 'skill',
  rarity: 'uncommon',
  cost: 2,
  target: 'none',
  exhaust: true,
  effects: [
    { kind: 'applyStatus', status: 'poison', stacks: 4, target: 'allEnemies' },
    { kind: 'applyStatus', status: 'weak', stacks: 2, target: 'allEnemies' },
  ],
  upgrade: {
    effects: [
      { kind: 'applyStatus', status: 'poison', stacks: 7, target: 'allEnemies' },
      { kind: 'applyStatus', status: 'weak', stacks: 2, target: 'allEnemies' },
    ],
  },
});

define({
  id: 'twin_fangs',
  name: 'Twin Fangs',
  type: 'attack',
  rarity: 'rare',
  cost: 2,
  target: 'enemy',
  effects: [
    { kind: 'damage', amount: 6, times: 2 },
    { kind: 'applyStatus', status: 'poison', stacks: 4, target: 'enemy' },
  ],
  upgrade: {
    effects: [
      { kind: 'damage', amount: 8, times: 2 },
      { kind: 'applyStatus', status: 'poison', stacks: 6, target: 'enemy' },
    ],
  },
});

// --- Silent card-set port (wiki values; simplifications noted per card) ---

define({
  id: 'bane',
  name: 'Bane',
  type: 'attack',
  rarity: 'common',
  cost: 1,
  target: 'enemy',
  effects: [
    { kind: 'damage', amount: 7 },
    { kind: 'damage', amount: 7, onlyIfTargetPoisoned: true },
  ],
  upgrade: {
    effects: [
      { kind: 'damage', amount: 10 },
      { kind: 'damage', amount: 10, onlyIfTargetPoisoned: true },
    ],
  },
});

define({
  id: 'dagger_spray',
  name: 'Dagger Spray',
  type: 'attack',
  rarity: 'common',
  cost: 1,
  target: 'none',
  effects: [{ kind: 'damage', amount: 4, times: 2, target: 'allEnemies' }],
  upgrade: { effects: [{ kind: 'damage', amount: 6, times: 2, target: 'allEnemies' }] },
});

define({
  // Original lets you choose the discard; this engine discards at random.
  id: 'dagger_throw',
  name: 'Dagger Throw',
  type: 'attack',
  rarity: 'common',
  cost: 1,
  target: 'enemy',
  effects: [
    { kind: 'damage', amount: 9 },
    { kind: 'draw', count: 1 },
    { kind: 'discardRandom', count: 1 },
  ],
  upgrade: {
    effects: [
      { kind: 'damage', amount: 12 },
      { kind: 'draw', count: 1 },
      { kind: 'discardRandom', count: 1 },
    ],
  },
});

define({
  id: 'deflect',
  name: 'Deflect',
  type: 'skill',
  rarity: 'common',
  cost: 0,
  target: 'none',
  effects: [{ kind: 'block', amount: 4 }],
  upgrade: { effects: [{ kind: 'block', amount: 7 }] },
});

define({
  id: 'dodge_and_roll',
  name: 'Dodge and Roll',
  type: 'skill',
  rarity: 'common',
  cost: 1,
  target: 'none',
  effects: [
    { kind: 'block', amount: 4 },
    { kind: 'applyStatus', status: 'nextTurnBlock', stacks: 4, target: 'self' },
  ],
  upgrade: {
    effects: [
      { kind: 'block', amount: 6 },
      { kind: 'applyStatus', status: 'nextTurnBlock', stacks: 6, target: 'self' },
    ],
  },
});

define({
  id: 'flying_knee',
  name: 'Flying Knee',
  type: 'attack',
  rarity: 'common',
  cost: 1,
  target: 'enemy',
  effects: [
    { kind: 'damage', amount: 8 },
    { kind: 'applyStatus', status: 'nextTurnEnergy', stacks: 1, target: 'self' },
  ],
  upgrade: {
    effects: [
      { kind: 'damage', amount: 11 },
      { kind: 'applyStatus', status: 'nextTurnEnergy', stacks: 1, target: 'self' },
    ],
  },
});

define({
  id: 'outmaneuver',
  name: 'Outmaneuver',
  type: 'skill',
  rarity: 'common',
  cost: 1,
  target: 'none',
  effects: [{ kind: 'applyStatus', status: 'nextTurnEnergy', stacks: 2, target: 'self' }],
  upgrade: { effects: [{ kind: 'applyStatus', status: 'nextTurnEnergy', stacks: 3, target: 'self' }] },
});

define({
  // Original: enemies lose 6 strength this turn only. No temporary-strength
  // mechanic here, so it is a smaller permanent loss instead.
  id: 'piercing_wail',
  name: 'Piercing Wail',
  type: 'skill',
  rarity: 'common',
  cost: 1,
  target: 'none',
  exhaust: true,
  effects: [{ kind: 'applyStatus', status: 'strength', stacks: -2, target: 'allEnemies' }],
  upgrade: { effects: [{ kind: 'applyStatus', status: 'strength', stacks: -3, target: 'allEnemies' }] },
});

define({
  id: 'slice',
  name: 'Slice',
  type: 'attack',
  rarity: 'common',
  cost: 0,
  target: 'enemy',
  effects: [{ kind: 'damage', amount: 6 }],
  upgrade: { effects: [{ kind: 'damage', amount: 9 }] },
});

define({
  // Discard is random here (original: chosen).
  id: 'acrobatics',
  name: 'Acrobatics',
  type: 'skill',
  rarity: 'common',
  cost: 1,
  target: 'none',
  effects: [
    { kind: 'draw', count: 3 },
    { kind: 'discardRandom', count: 1 },
  ],
  upgrade: {
    effects: [
      { kind: 'draw', count: 4 },
      { kind: 'discardRandom', count: 1 },
    ],
  },
});

define({
  // Discard is random here (original: chosen).
  id: 'prepared',
  name: 'Prepared',
  type: 'skill',
  rarity: 'common',
  cost: 0,
  target: 'none',
  effects: [
    { kind: 'draw', count: 1 },
    { kind: 'discardRandom', count: 1 },
  ],
  upgrade: {
    effects: [
      { kind: 'draw', count: 2 },
      { kind: 'discardRandom', count: 2 },
    ],
  },
});

define({
  id: 'accuracy',
  name: 'Accuracy',
  type: 'power',
  rarity: 'uncommon',
  cost: 1,
  target: 'none',
  effects: [{ kind: 'applyStatus', status: 'accuracy', stacks: 4, target: 'self' }],
  upgrade: { effects: [{ kind: 'applyStatus', status: 'accuracy', stacks: 6, target: 'self' }] },
});

define({
  id: 'all_out_attack',
  name: 'All-Out Attack',
  type: 'attack',
  rarity: 'uncommon',
  cost: 1,
  target: 'none',
  effects: [
    { kind: 'damage', amount: 10, target: 'allEnemies' },
    { kind: 'discardRandom', count: 1 },
  ],
  upgrade: {
    effects: [
      { kind: 'damage', amount: 14, target: 'allEnemies' },
      { kind: 'discardRandom', count: 1 },
    ],
  },
});

define({
  id: 'backstab',
  name: 'Backstab',
  type: 'attack',
  rarity: 'uncommon',
  cost: 0,
  target: 'enemy',
  innate: true,
  exhaust: true,
  effects: [{ kind: 'damage', amount: 11 }],
  upgrade: { effects: [{ kind: 'damage', amount: 15 }] },
});

define({
  id: 'blur',
  name: 'Blur',
  type: 'skill',
  rarity: 'uncommon',
  cost: 1,
  target: 'none',
  effects: [
    { kind: 'block', amount: 5 },
    { kind: 'applyStatus', status: 'blur', stacks: 1, target: 'self' },
  ],
  upgrade: {
    effects: [
      { kind: 'block', amount: 8 },
      { kind: 'applyStatus', status: 'blur', stacks: 1, target: 'self' },
    ],
  },
});

define({
  id: 'bouncing_flask',
  name: 'Bouncing Flask',
  type: 'skill',
  rarity: 'uncommon',
  cost: 2,
  target: 'none',
  effects: [
    { kind: 'applyStatus', status: 'poison', stacks: 3, target: 'randomEnemy' },
    { kind: 'applyStatus', status: 'poison', stacks: 3, target: 'randomEnemy' },
    { kind: 'applyStatus', status: 'poison', stacks: 3, target: 'randomEnemy' },
  ],
  upgrade: {
    effects: [
      { kind: 'applyStatus', status: 'poison', stacks: 3, target: 'randomEnemy' },
      { kind: 'applyStatus', status: 'poison', stacks: 3, target: 'randomEnemy' },
      { kind: 'applyStatus', status: 'poison', stacks: 3, target: 'randomEnemy' },
      { kind: 'applyStatus', status: 'poison', stacks: 3, target: 'randomEnemy' },
    ],
  },
});

define({
  id: 'catalyst',
  name: 'Catalyst',
  type: 'skill',
  rarity: 'uncommon',
  cost: 1,
  target: 'enemy',
  exhaust: true,
  effects: [{ kind: 'multiplyStatus', status: 'poison', factor: 2 }],
  upgrade: { effects: [{ kind: 'multiplyStatus', status: 'poison', factor: 3 }] },
});

define({
  // Counts the attacks played this turn, including Finisher itself.
  id: 'finisher',
  name: 'Finisher',
  type: 'attack',
  rarity: 'uncommon',
  cost: 1,
  target: 'enemy',
  effects: [{ kind: 'damage', amount: 6, times: 'attacksThisTurn' }],
  upgrade: { effects: [{ kind: 'damage', amount: 8, times: 'attacksThisTurn' }] },
});

define({
  id: 'flechettes',
  name: 'Flechettes',
  type: 'attack',
  rarity: 'uncommon',
  cost: 1,
  target: 'enemy',
  effects: [{ kind: 'damage', amount: 4, times: 'skillsInHand' }],
  upgrade: { effects: [{ kind: 'damage', amount: 6, times: 'skillsInHand' }] },
});

define({
  id: 'infinite_blades',
  name: 'Infinite Blades',
  type: 'power',
  rarity: 'uncommon',
  cost: 1,
  target: 'none',
  effects: [{ kind: 'applyStatus', status: 'infiniteBlades', stacks: 1, target: 'self' }],
  upgrade: { innate: true },
});

define({
  id: 'leg_sweep',
  name: 'Leg Sweep',
  type: 'skill',
  rarity: 'uncommon',
  cost: 2,
  target: 'enemy',
  effects: [
    { kind: 'applyStatus', status: 'weak', stacks: 2, target: 'enemy' },
    { kind: 'block', amount: 11 },
  ],
  upgrade: {
    effects: [
      { kind: 'applyStatus', status: 'weak', stacks: 3, target: 'enemy' },
      { kind: 'block', amount: 14 },
    ],
  },
});

define({
  id: 'predator',
  name: 'Predator',
  type: 'attack',
  rarity: 'uncommon',
  cost: 2,
  target: 'enemy',
  effects: [
    { kind: 'damage', amount: 15 },
    { kind: 'applyStatus', status: 'nextTurnDraw', stacks: 2, target: 'self' },
  ],
  upgrade: {
    effects: [
      { kind: 'damage', amount: 20 },
      { kind: 'applyStatus', status: 'nextTurnDraw', stacks: 2, target: 'self' },
    ],
  },
});

define({
  id: 'riddle_with_holes',
  name: 'Riddle with Holes',
  type: 'attack',
  rarity: 'uncommon',
  cost: 2,
  target: 'enemy',
  effects: [{ kind: 'damage', amount: 3, times: 5 }],
  upgrade: { effects: [{ kind: 'damage', amount: 4, times: 5 }] },
});

define({
  id: 'thousand_cuts',
  name: 'A Thousand Cuts',
  type: 'power',
  rarity: 'rare',
  cost: 2,
  target: 'none',
  effects: [{ kind: 'applyStatus', status: 'thousandCuts', stacks: 1, target: 'self' }],
  upgrade: { effects: [{ kind: 'applyStatus', status: 'thousandCuts', stacks: 2, target: 'self' }] },
});

define({
  id: 'after_image',
  name: 'After Image',
  type: 'power',
  rarity: 'rare',
  cost: 1,
  target: 'none',
  effects: [{ kind: 'applyStatus', status: 'afterImage', stacks: 1, target: 'self' }],
  upgrade: { innate: true },
});

define({
  id: 'envenom',
  name: 'Envenom',
  type: 'power',
  rarity: 'rare',
  cost: 2,
  target: 'none',
  effects: [{ kind: 'applyStatus', status: 'envenom', stacks: 1, target: 'self' }],
  upgrade: { cost: 1 },
});

define({
  id: 'grand_finale',
  name: 'Grand Finale',
  type: 'attack',
  rarity: 'rare',
  cost: 0,
  target: 'none',
  playCondition: 'drawPileEmpty',
  effects: [{ kind: 'damage', amount: 50, target: 'allEnemies' }],
  upgrade: { effects: [{ kind: 'damage', amount: 60, target: 'allEnemies' }] },
});

define({
  // Original: draw 1 then choose a discard; discard is random here.
  id: 'tools_of_the_trade',
  name: 'Tools of the Trade',
  type: 'power',
  rarity: 'rare',
  cost: 1,
  target: 'none',
  effects: [{ kind: 'applyStatus', status: 'toolsOfTrade', stacks: 1, target: 'self' }],
  upgrade: { cost: 0 },
});

define({
  id: 'unload',
  name: 'Unload',
  type: 'attack',
  rarity: 'rare',
  cost: 1,
  target: 'enemy',
  effects: [
    { kind: 'damage', amount: 14 },
    { kind: 'discardNonAttacks' },
  ],
  upgrade: {
    effects: [
      { kind: 'damage', amount: 18 },
      { kind: 'discardNonAttacks' },
    ],
  },
});

define({
  id: 'wraith_form',
  name: 'Wraith Form',
  type: 'power',
  rarity: 'rare',
  cost: 3,
  target: 'none',
  effects: [
    { kind: 'applyStatus', status: 'intangible', stacks: 2, target: 'self' },
    { kind: 'applyStatus', status: 'wraithForm', stacks: 1, target: 'self' },
  ],
  upgrade: {
    effects: [
      { kind: 'applyStatus', status: 'intangible', stacks: 3, target: 'self' },
      { kind: 'applyStatus', status: 'wraithForm', stacks: 1, target: 'self' },
    ],
  },
});

// --- Character card pools ---
// Cards not listed in either pool are neutral and offered to every character.
// Data lives here (not per-define) so the split is auditable in one place.

const WARRIOR_CARDS = [
  'bash', 'cleave', 'pommel_strike', 'twin_strike', 'iron_wave', 'shrug_it_off',
  'inflame', 'bludgeon', 'offering', 'anger', 'wild_strike', 'reckless_charge',
  'heavy_armor', 'bloodletting', 'battle_trance', 'clothesline', 'uppercut',
  'hemokinesis', 'pummel', 'disarm', 'flex', 'shockwave', 'seeing_red',
  'entrench', 'barricade', 'demon_form', 'berserk', 'whirlwind', 'metallicize',
  'heavy_blade', 'emergency_guard', 'intimidate', 'impervious',
];
const ASSASSIN_CARDS = [
  'neutralize', 'survivor', 'sucker_punch', 'backflip', 'cloak_and_dagger',
  'quick_slash', 'flurry', 'trip', 'deadly_venom', 'venom_strike',
  'noxious_blast', 'blade_dance', 'dash', 'skewer', 'terror', 'footwork',
  'caltrops', 'crippling_cloud', 'die_die_die', 'adrenaline', 'noxious_fumes',
  'twin_fangs',
  // Silent-set port
  'bane', 'dagger_spray', 'dagger_throw', 'deflect', 'dodge_and_roll',
  'flying_knee', 'outmaneuver', 'piercing_wail', 'slice', 'acrobatics',
  'prepared', 'accuracy', 'all_out_attack', 'backstab', 'blur',
  'bouncing_flask', 'catalyst', 'finisher', 'flechettes', 'infinite_blades',
  'leg_sweep', 'predator', 'riddle_with_holes', 'thousand_cuts', 'after_image',
  'envenom', 'grand_finale', 'tools_of_the_trade', 'unload', 'wraith_form',
];
for (const id of WARRIOR_CARDS) getCardDef(id).character = 'warrior';
for (const id of ASSASSIN_CARDS) getCardDef(id).character = 'assassin';

/** Reward/shop pool: playable cards of a rarity available to this character. */
export function cardPool(character: CharacterId, rarity: CardRarity): string[] {
  return Object.values(CARDS)
    .filter((c) => c.rarity === rarity && !c.unplayable && (!c.character || c.character === character))
    .map((c) => c.id);
}

export function getCardDef(defId: string): CardDef {
  const def = CARDS[defId];
  if (!def) throw new Error(`Unknown card: ${defId}`);
  return def;
}

/** Resolves an instance to its effective definition, applying upgrade overrides. */
export function resolveCard(card: CardInstance): CardDef {
  const def = getCardDef(card.defId);
  if (!card.upgraded || !def.upgrade) return def;
  return { ...def, ...def.upgrade, name: `${def.name}+` };
}

let nextInstanceId = 1;

export function makeCard(defId: string, upgraded = false): CardInstance {
  getCardDef(defId); // validate id early
  return { instanceId: nextInstanceId++, defId, upgraded };
}

/** After loading a save, keep new instance ids above the loaded ones. */
export function ensureInstanceIdAbove(maxSeen: number): void {
  if (maxSeen >= nextInstanceId) nextInstanceId = maxSeen + 1;
}

/** The character's starting deck (defaults to the warrior's 5/4/1 kit). */
export function makeStarterDeck(character: CharacterId = 'warrior'): CardInstance[] {
  return getCharacterDef(character).starterCards.map((id) => makeCard(id));
}
