import type { CardDef, CardInstance } from './types';

/**
 * Card database. Data-driven: adding a card means adding an entry here.
 * Descriptions are generated by the UI layer from effects, not stored here.
 */
export const CARDS: Record<string, CardDef> = {};

function define(def: CardDef): void {
  if (CARDS[def.id]) throw new Error(`Duplicate card id: ${def.id}`);
  CARDS[def.id] = def;
}

define({
  id: 'strike',
  name: 'Strike',
  type: 'attack',
  rarity: 'starter',
  cost: 1,
  target: 'enemy',
  effects: [{ kind: 'damage', amount: 6 }],
  upgrade: { effects: [{ kind: 'damage', amount: 9 }] },
});

define({
  id: 'defend',
  name: 'Defend',
  type: 'skill',
  rarity: 'starter',
  cost: 1,
  target: 'none',
  effects: [{ kind: 'block', amount: 5 }],
  upgrade: { effects: [{ kind: 'block', amount: 8 }] },
});

define({
  id: 'bash',
  name: 'Bash',
  type: 'attack',
  rarity: 'starter',
  cost: 2,
  target: 'enemy',
  effects: [
    { kind: 'damage', amount: 8 },
    { kind: 'applyStatus', status: 'vulnerable', stacks: 2, target: 'enemy' },
  ],
  upgrade: {
    effects: [
      { kind: 'damage', amount: 10 },
      { kind: 'applyStatus', status: 'vulnerable', stacks: 3, target: 'enemy' },
    ],
  },
});

define({
  id: 'cleave',
  name: 'Cleave',
  type: 'attack',
  rarity: 'common',
  cost: 1,
  target: 'none',
  effects: [{ kind: 'damage', amount: 8, target: 'allEnemies' }],
  upgrade: { effects: [{ kind: 'damage', amount: 11, target: 'allEnemies' }] },
});

define({
  id: 'pommel_strike',
  name: 'Pommel Strike',
  type: 'attack',
  rarity: 'common',
  cost: 1,
  target: 'enemy',
  effects: [
    { kind: 'damage', amount: 9 },
    { kind: 'draw', count: 1 },
  ],
  upgrade: {
    effects: [
      { kind: 'damage', amount: 10 },
      { kind: 'draw', count: 2 },
    ],
  },
});

define({
  id: 'twin_strike',
  name: 'Twin Strike',
  type: 'attack',
  rarity: 'common',
  cost: 1,
  target: 'enemy',
  effects: [{ kind: 'damage', amount: 5, times: 2 }],
  upgrade: { effects: [{ kind: 'damage', amount: 7, times: 2 }] },
});

define({
  id: 'iron_wave',
  name: 'Iron Wave',
  type: 'attack',
  rarity: 'common',
  cost: 1,
  target: 'enemy',
  effects: [
    { kind: 'damage', amount: 5 },
    { kind: 'block', amount: 5 },
  ],
  upgrade: {
    effects: [
      { kind: 'damage', amount: 7 },
      { kind: 'block', amount: 7 },
    ],
  },
});

define({
  id: 'shrug_it_off',
  name: 'Shrug It Off',
  type: 'skill',
  rarity: 'common',
  cost: 1,
  target: 'none',
  effects: [
    { kind: 'block', amount: 8 },
    { kind: 'draw', count: 1 },
  ],
  upgrade: {
    effects: [
      { kind: 'block', amount: 11 },
      { kind: 'draw', count: 1 },
    ],
  },
});

define({
  id: 'deadly_venom',
  name: 'Deadly Venom',
  type: 'skill',
  rarity: 'uncommon',
  cost: 1,
  target: 'enemy',
  effects: [{ kind: 'applyStatus', status: 'poison', stacks: 5, target: 'enemy' }],
  upgrade: { effects: [{ kind: 'applyStatus', status: 'poison', stacks: 7, target: 'enemy' }] },
});

define({
  id: 'inflame',
  name: 'Inflame',
  type: 'power',
  rarity: 'uncommon',
  cost: 1,
  target: 'none',
  effects: [{ kind: 'applyStatus', status: 'strength', stacks: 2, target: 'self' }],
  upgrade: { effects: [{ kind: 'applyStatus', status: 'strength', stacks: 3, target: 'self' }] },
});

define({
  id: 'bludgeon',
  name: 'Bludgeon',
  type: 'attack',
  rarity: 'rare',
  cost: 3,
  target: 'enemy',
  effects: [{ kind: 'damage', amount: 32 }],
  upgrade: { effects: [{ kind: 'damage', amount: 42 }] },
});

define({
  id: 'offering',
  name: 'Offering',
  type: 'skill',
  rarity: 'rare',
  cost: 0,
  target: 'none',
  exhaust: true,
  effects: [
    { kind: 'loseHp', amount: 6 },
    { kind: 'gainEnergy', amount: 2 },
    { kind: 'draw', count: 3 },
  ],
  upgrade: {
    effects: [
      { kind: 'loseHp', amount: 6 },
      { kind: 'gainEnergy', amount: 2 },
      { kind: 'draw', count: 5 },
    ],
  },
});

// --- Status & curse cards (unplayable junk that clogs the deck) ---

define({
  id: 'wound',
  name: 'Wound',
  type: 'status',
  rarity: 'special',
  cost: 0,
  target: 'none',
  unplayable: true,
  effects: [],
});

define({
  id: 'burn',
  name: 'Burn',
  type: 'status',
  rarity: 'special',
  cost: 0,
  target: 'none',
  unplayable: true,
  selfDamageAtTurnEnd: 2,
  effects: [],
});

define({
  id: 'injury',
  name: 'Injury',
  type: 'curse',
  rarity: 'special',
  cost: 0,
  target: 'none',
  unplayable: true,
  effects: [],
});

// --- Day 2 playable cards ---

define({
  id: 'whirlwind',
  name: 'Whirlwind',
  type: 'attack',
  rarity: 'uncommon',
  cost: 'x',
  target: 'none',
  effects: [{ kind: 'damage', amount: 5, times: 'x', target: 'allEnemies' }],
  upgrade: { effects: [{ kind: 'damage', amount: 8, times: 'x', target: 'allEnemies' }] },
});

define({
  id: 'metallicize',
  name: 'Metallicize',
  type: 'power',
  rarity: 'uncommon',
  cost: 1,
  target: 'none',
  effects: [{ kind: 'applyStatus', status: 'metallicize', stacks: 3, target: 'self' }],
  upgrade: { effects: [{ kind: 'applyStatus', status: 'metallicize', stacks: 4, target: 'self' }] },
});

define({
  id: 'dramatic_entrance',
  name: 'Dramatic Entrance',
  type: 'attack',
  rarity: 'uncommon',
  cost: 0,
  target: 'none',
  innate: true,
  exhaust: true,
  effects: [{ kind: 'damage', amount: 8, target: 'allEnemies' }],
  upgrade: { effects: [{ kind: 'damage', amount: 12, target: 'allEnemies' }] },
});

export function getCardDef(defId: string): CardDef {
  const def = CARDS[defId];
  if (!def) throw new Error(`Unknown card: ${defId}`);
  return def;
}

/** Resolves an instance to its effective definition, applying upgrade overrides. */
export function resolveCard(card: CardInstance): CardDef {
  const def = getCardDef(card.defId);
  if (!card.upgraded || !def.upgrade) return def;
  return { ...def, ...def.upgrade, name: `${def.name}+` };
}

let nextInstanceId = 1;

export function makeCard(defId: string, upgraded = false): CardInstance {
  getCardDef(defId); // validate id early
  return { instanceId: nextInstanceId++, defId, upgraded };
}

/** After loading a save, keep new instance ids above the loaded ones. */
export function ensureInstanceIdAbove(maxSeen: number): void {
  if (maxSeen >= nextInstanceId) nextInstanceId = maxSeen + 1;
}

/** The starting deck: 5 Strikes, 4 Defends, 1 Bash. */
export function makeStarterDeck(): CardInstance[] {
  const deck: CardInstance[] = [];
  for (let i = 0; i < 5; i++) deck.push(makeCard('strike'));
  for (let i = 0; i < 4; i++) deck.push(makeCard('defend'));
  deck.push(makeCard('bash'));
  return deck;
}
